# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ashleytharp/projects/learnding/singleton_sysinfo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ashleytharp/projects/learnding/singleton_sysinfo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ashleytharp/projects/learnding/singleton_sysinfo/CMakeFiles /Users/ashleytharp/projects/learnding/singleton_sysinfo/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ashleytharp/projects/learnding/singleton_sysinfo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named sysinfo

# Build rule for target.
sysinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sysinfo
.PHONY : sysinfo

# fast build rule for target.
sysinfo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysinfo.dir/build.make CMakeFiles/sysinfo.dir/build
.PHONY : sysinfo/fast

app/main.o: app/main.cpp.o

.PHONY : app/main.o

# target to build an object file
app/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/app/main.cpp.o
.PHONY : app/main.cpp.o

app/main.i: app/main.cpp.i

.PHONY : app/main.i

# target to preprocess a source file
app/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/app/main.cpp.i
.PHONY : app/main.cpp.i

app/main.s: app/main.cpp.s

.PHONY : app/main.s

# target to generate assembly for a file
app/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/app/main.cpp.s
.PHONY : app/main.cpp.s

srcs/SysInfo.o: srcs/SysInfo.cpp.o

.PHONY : srcs/SysInfo.o

# target to build an object file
srcs/SysInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysinfo.dir/build.make CMakeFiles/sysinfo.dir/srcs/SysInfo.cpp.o
.PHONY : srcs/SysInfo.cpp.o

srcs/SysInfo.i: srcs/SysInfo.cpp.i

.PHONY : srcs/SysInfo.i

# target to preprocess a source file
srcs/SysInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysinfo.dir/build.make CMakeFiles/sysinfo.dir/srcs/SysInfo.cpp.i
.PHONY : srcs/SysInfo.cpp.i

srcs/SysInfo.s: srcs/SysInfo.cpp.s

.PHONY : srcs/SysInfo.s

# target to generate assembly for a file
srcs/SysInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sysinfo.dir/build.make CMakeFiles/sysinfo.dir/srcs/SysInfo.cpp.s
.PHONY : srcs/SysInfo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... sysinfo"
	@echo "... app/main.o"
	@echo "... app/main.i"
	@echo "... app/main.s"
	@echo "... srcs/SysInfo.o"
	@echo "... srcs/SysInfo.i"
	@echo "... srcs/SysInfo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

